{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fwdselect
  version: {{ version|replace("-", "_") }}

source:
  fn: FWDselect_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/FWDselect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FWDselect/FWDselect_{{ version }}.tar.gz
  sha256: e77313b3066806333edec3904d05e4fd51b596737edc337ba4019ecf609d1070

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cvtools
    - r-mgcv
  run:
    - r-base
    - r-cvtools
    - r-mgcv

test:
  commands:
    - $R -e "library('FWDselect')"           # [not win]
    - "\"%R%\" -e \"library('FWDselect')\""  # [win]

about:
  home: http://cran.r-project.org/package=FWDselect
  license: MIT
  summary: A simple method to select the best model or best subset of variables using different
    types of data (binary, Gaussian or Poisson) and applying it in different contexts
    (parametric or non-parametric).
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
