travis:
  secure:
    BINSTAR_TOKEN: j4BI8cDodCp2K6bM7HUHbIVEzHxyyKAOqOp1mQTuN0eLx75ysrMv3kqFbJs1z7VY7FUl6p4AEVISbdYQMaswA2UxXx1XgGddGxMZmHW5K+RJcQ8ghFWpvWy/Wxpj/w2prbhTb8MW8dlpg7wqVcUSsFfHdD18TNMP91prq2oNkI1Xhj8NZkMYfXaXpPJgzhOIAZWUaQP0i6nKWQq8BAhBnvlQGe6UKKtWw9aN/PLEpmPOkMzrIAUcot5OWafAdXLOzBv6fE5Lk1+mjNllHuCpq7gXERsXuvG6zMp3s9eXdW+zipqCnCQiUB+tiipmx9cVBwSIL+AWpbcStNgzq/Ki+VekqiN7pn7B54ok0O+7Xh1GbJGmozNRX4ARw+xBxwvv8uyxsjCGZrlo0aORaLVIKyDaoWxPvPtK70rijd4cvMjTJUc5MrXV/ffGVqnnf0yZs68zRT0tJXPB2xaphXmGptR82rJDQ9qqfADQeCytURhyslj1Wgb7r38a1b0E0dC4W+lc5wR1gep8/C28ymq2HmPrKkBKuZZYjuxhBpFbo76Vv3KOYSQhC0fn1XrGFR1iiiUWVrHdOfE96/efVessg1HBLb8AIjpZS5gGzdGQ/h1EQQtstzclcAcE4L8EJTYPDIx5wsPFuQNW+absKdVHKKmFudesBMBNcqNeyolSLww=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
